---
- name: Rpm get package
    shell: rpm -Uvh https://repo.zabbix.com/zabbix/6.2/rhel/8/x86_64/zabbix-release-6.2-3.el8.noarch.rpm
    when: "'zabbix-agent' not in services"
    tags: zabbix-agent

  - name: Dnf install zabbix-agent
    dnf:
      name: zabbix-agent
      state: present
    when: "'zabbix-agent' not in services"
    tags: zabbix-agent

  - name: Dnf install zabbix-agent
    dnf:
      name: "{{ item }}"
      state: latest
    loop:
      - 'epel-release'
      - 'clamav'
      - 'clamd'
      - 'clamav-update'
    tags: clamav