---
- name: Set permissions
  shell: "{{ item }}"
  loop:
    - ''setsebool -P antivirus_can_scan_system 1
    - 'sed -i 's/#LocalSocket \/run/LocalSocket \/run/g' /etc/clamd.d/scan.conf'

- name: Copy conf
  copy:
    src: ../files/scan_config.conf
    dst: /usr/lib/systemd/system/freshclam.service