---
- name: Install packages for specific OS
  include_tasks: "{{ ansible_os_family }}.yml"
  tags: 
    - zabbix-agent
    - clamav

- name: Configure Zabbix-agent
  include_tasks: 'zabbix-agent.yml'
  tags: zabbix-agent

- name: Configure clamav
  include_tasks: 'clamav.yml'
  tags: clamav