---
- name: Rpm get package
  shell: "{{ item }}"
  tags: zabbix-agent
  loop:
    - 'wget https://repo.zabbix.com/zabbix/6.2/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.2-4%2Bubuntu20.04_all.deb'
    - 'dpkg -i zabbix-release_6.2-4+ubuntu20.04_all.deb'
    - 'apt update'

- name: Apt install zabbix-agent
  apt:
    name: zabbix-agent
    state: present
  tags: zabbix-agent

- name: Apt install clamav
  apt:
    name: "{{ item }}"
    state: latest
  loop:
    - 'clamav'
    - 'clamav-daemon'
  tags: clamav