---
#ansible-playbook zabbix_agent.yaml -i ../inventory --ask-pass --ask-become-pass
- name: setup zabbix agent
  hosts: webserver
  become: true
  vars:
    zabbix_server: hostvars[zabbixserver]['ansible_default_ipv4']['address']
  tasks:
  - name: Zabbix agent install
    shell: rpm -Uvh https://repo.zabbix.com/zabbix/6.2/rhel/8/x86_64/zabbix-release-6.2-3.el8.noarch.rpm

  - name: Dnf install zabbix-agent
    dnf:
      name: zabbix-agent
      state: present

  - name: "Ansible Lineinfile Multiple Lines"
    lineinfile:
      path: /etc/zabbix/zabbix_agentd.conf
      regexp: '{{item.From}}'
      line: '{{item.To}}'
      state: present  
    with_items:
      - { From: 'Server=', To: 'Server={{ zabbix_server }}'}
      - { From: 'ServerActive=', To: 'ServerActive={{ zabbix_server }}'}
      - { From: 'Hostname=', To: 'Hostname={{ ansible_hostname }}'}

  - name: Open port 10050 for zabbix-server
    ansible.posix.firewalld:
      port: 10050/tcp
      permanent: yes
      state: enabled

  - name: Restart zabbix
    ansible.builtin.service:
      name: zabbix-agent
      state: enabled

  - name: Restart zabbix
    ansible.builtin.service:
      name: zabbix-agent
      state: restarted